language: python

python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'

install:
  - pip install pyproj==1.9.6

script:
  - python testdocs.py
  
deploy:
  provider: pypi
  user: "kbahgat"
  password:
    secure: "puOB4zUdgFnu744Um+9m+wrDWJr6xcca0EhHsGp7PF+i5HhwxU3chSS+2E4O5Vpd9C6w9VebY0/dEu8sl4/BAZALe5o3szhNeWNfizynM7fTBBltrTBwMftQLXN3x4++4Ut5RivUZloKTN8g39EoBZ5ODroDn03JAem0nRygTk8SHObAQDkP13HrzsD8NV3APn/VM9qVWCT1cHoocT7wufmXZuKWi99A+GITcO99Q+FZTcfUQ3xjvHjn6R8fFw6sxETX8pQtxGV13O9sfdJpMZif1nJg9iXhKgZF3VrfYo6eN227I2a/pzAeEpjQHUyHBi5ZJeVv+GEM+jFVc5fr6VXe5YKFe0R9Y7hEOEOG51JNm8UU56cZ+Pcd0XQ06wuCWxc9n1V29HCcjMCF5bq3f0oP73KnfCKsZirghLx910OKTQWjIEOGzcZbJLMksylgpxllPglvvyS4Ge/QRllbunMMlVx3KKwoIjSgck6oo3pxoWBwTdtyXBmoS+CFuJOF4yB84Rh185yf4Fvj2Le1TSHMXU2bUo3McT6v1wbzwdq+P49Mnyp60MhU9SrwCFV4rXFzeJn/527eEVWR9OGnQZqyGqYCStzb/3OGH6+B+DZ84Vbp4tZOz00Yqj75ty96uJnw9TEEoOhzbcZBCHCo8+tWFwO+blKcGJOXqBeXqto="
  on:
    tags: true
    distributions: "sdist bdist_wheel"
  
  